services:
  wg-easy:
    environment:
      # ⚠️  Required:
      - WG_HOST=HOSTNAME.DOMAIN

      # Optional:
      - PASSWORD=zPod@izAmazing2024!
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=192.168.250.x
      - WG_DEFAULT_DNS=IPADDRESS,DOMAIN
      - WG_ALLOWED_IPS=10.0.0.0/8

    image: ghcr.io/wg-easy/wg-easy
    container_name: wireguard
    volumes:
      - ./config:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
